### ISSUE TITLE
crash with `kubectl config set-credentials oidc ...`

### ISSUE THREAD

**Issue by bmm-alc** [int128/kubelogin#728]
## Describe the issue
I can login on my OIDC IDP web interface but when I enter the command kubectl output after `oidc-login setup` I get a crash

## To reproduce
```
kubectl config set-credentials oidc \
  --exec-api-version=client.authentication.k8s.io/v1beta1 \
  --exec-command=kubectl \
  --exec-arg=oidc-login \
  --exec-arg=get-token \
  --exec-arg=--oidc-issuer-url=https://accounts.google.com \
  --exec-arg=--oidc-client-id=xxxxxxxxxxxxx.apps.googleusercontent.com \
  --exec-arg=--oidc-client-secret=xxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x40f71c]

goroutine 1 [running]:
reflect.mapiternext(0xc0002143f0?)
	/usr/lib/golang/src/runtime/map.go:1378 +0x19
k8s.io/kubernetes/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x3?)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0008b9da0, 0xc000699ba0, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_map.go:297 +0x31a
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x186fcc0?, 0xc0000db201?, 0xc000181578?)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000987920, 0x173319e?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc000987a70, 0x7fff8af7f13a?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x186fcc0?, 0x824201?, 0xc000181578?)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000987ce0, 0x16e31be?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc000987d40, 0x17fa100?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0000d58a8, 0xc00003ad68, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x302
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00098a870, 0x16e99cb?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc00098a960, 0x0?, 0xc000181560)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc00020ea00?, 0x0?, 0x0?)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0007935e0, 0xc00003ad10, 0xc00027afc0?)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:219 +0x82
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc000181560, {0x1916d00, 0xc00003ad10})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:98 +0x158
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00020ea00, {0x1916d00, 0xc00003ad10})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/config.go:299 +0xc9
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x16c2e80?, {0x1d39e88?, 0xc00003ad10?}, {0x1d30420, 0xc0008b83c0})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0003c0460, {0x1d39e88, 0xc00003ad10}, {0x1d30420, 0xc0008b83c0})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0004415e0, {0x1d39e38?, 0xc0001814a0}, {0x1d30420, 0xc0008b83c0})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0004415e0, {0x1d39e38, 0xc0001814a0}, {0x1d30420, 0xc0008b83c0})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7fc7113b1118, 0xc0004415e0}, {0x1d39e38, 0xc0001814a0})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:50 +0x64
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:466
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0007fdc50}, 0xc0007fdc80, 0xc0007fdcb0, 0xc0007fdce0, {0xc000539720, ...}, ...}, ...)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:419 +0xa8
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x1d4a318, 0xc0000bc460}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0007fd080}, 0xc0007fd0b0, 0xc0007fd0e0, ...}, ...)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/config.go:294 +0xcf8
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.createAuthInfoOptions.run({{0x1d4a318, 0xc0000bc460}, {0x7fff8af7f13a, 0x4}, {0x0, {0x0, 0x0}}, {0x0, {0x0, 0x0}}, ...})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:203 +0x31d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.newCmdConfigSetAuthInfo.func1(0xc0005d5080?, {0x1a8ddfa?, 0x8?, 0x8?})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:161 +0xf8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005d5080, {0xc00013bf80, 0x8, 0x8})
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x663
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00053ab00)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x39c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/kubernetes-cb303e613a121a29364f75cc67d3d580833a7479/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1bb

```

## Your environment
- OS: linux
- kubelogin version: v1.25.1
- kubectl version: v1.21.0 GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479
- OpenID Connect provider: Google

**Comment by bmm-alc** [comment]
Ok, the client was bugged, after an update of the system package, this is fixed.
